server:
  port: 9009

spring:
  application:
    name: department-service

  # MongoDB configuration
  data:
    mongodb:
      authentication-database: ${MONGODB_AUTH_DATABASE:admin}
      database: ${MONGODB_DATABASE:db}
      uri: ${MONGODB_URI:mongodb://user:pass@localhost:27017/db}